name: Print My Name

on:
  workflow_dispatch: # This allows the workflow to be run manually

jobs:
  print-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Printing name in console
        run: |
          echo "Hi, I am Noman"
          echo "I am an Engineer"
          echo "This is batch 1"
