name: Notify Slack

on:
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Slack
        run: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
