name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Chromium
          run: sudo apt-get install chromium-browser
        - uses: actions/setup-node@v1
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs