name: wdio-login-test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - name: Allure report action # Step to generate Allure report
          uses: simple-elf/allure-report-action@master
          if: always() # Execute even if previous steps fail
          with:
            allure_results: allure-results # Specify the directory containing Allure results
            allure_history: allure-history # Specify the directory to store Allure history
            keep_reports: 2 # Specify the number of previous reports to keep
        - name: Take Report
          uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: ./allure-report
        
